# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# org: aomcheer
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda-serverless-node

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"
